spring:
    datasource:
        hikari:
            driver-class-name: org.h2.Driver
            jdbc-url: jdbc:h2:mem:producer-consumer;DB_CLOSE_ON_EXIT=FALSE
            username: sa
            password:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: false
                hbm2ddl:
                    auto: create-drop
        open-in-view: false
    h2:
        console:
            enabled: true
